kind: Deployment
metadata:
  name: doings-deployment
  labels:
    app: doings-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: doings-app
  template:
    metadata:
      labels:
        app: doings-app
    spec:
      containers:
        - name: doings-container
          image: doingsacr.azurecr.io/nodejswebapp:v1
          ports:
            - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: doings-service
spec:
  selector:
    app: doings-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
